### ISSUE TITLE
Demo not working

### ISSUE THREAD

**Issue by sapter** [WebSeed/react-with-threejs-example#2]
Hi,

The link to your demo leads to a 404...

Thanks

**Comment by KorySchneider** [comment]
@sapter Had to change the github username in the URL, correct link:

https://willbamford.github.io/react-with-threejs-example/

**Comment by SHoar** [comment]
@willbamford Can you please update the link in your  description?

**Comment by willbamford** [comment]
Done, sorry I managed to miss the initial messages on this

**Comment by SHoar** [comment]
Thanks!
